apps/api/urls.py
from api.views import *
from rest_framework import routers

router = routers.SimpleRouter()

# API Projects
router.register(r'projects', ProjectViewSet, basename='projects')


urlpatterns = router.urls

apps/portfolio/urls.py
from django.urls import path
from .views import ProjectsListView, HomepageView, ContactView

app_name = 'portfolio'

urlpatterns = [

    path('', HomepageView.as_view(), name='home'),
    path('projects/', ProjectsListView.as_view(), name='projects'),
    path('contacts/', ContactView.as_view(), name='contacts'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),

    # API
    path('api/v2/', include('api.urls')),
]


if settings.DEBUG:
    if settings.MEDIA_ROOT:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/api/models.py
from django.db import models

# Create your models here.

apps/portfolio/models.py
from django.db import models


# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

apps/api/views.py
from rest_framework import viewsets

from api.permissions import IsAdminOrReadOnly
from api.serializers import ProjectSerializer

from portfolio.models import Project


class ProjectViewSet(viewsets.ModelViewSet):

    serializer_class = ProjectSerializer
    permission_classes = (IsAdminOrReadOnly, )

    def get_queryset(self):
        return Project.objects.all()

apps/portfolio/views.py
from django.views.generic import ListView, TemplateView

from .models import Project


class HomepageView(TemplateView):
    template_name = "portfolio_templates/homepage.html"


class ProjectsListView(ListView):
    model = Project
    template_name = "portfolio_templates/projects.html"
    context_object_name = "projects"

    def get_context_data(self, *, object_list=None, **kwargs):

        context = super().get_context_data(**kwargs)
        return context

    def get_queryset(self):
        return Project.objects.all()


class ContactView(TemplateView):
    template_name = "portfolio_templates/contacts.html"

templates/portfolio_templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    {% block head%}{% endblock %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/stylebase.css' %}">
    <link rel="icon" href="{% static 'icon.png' %}">
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-sm navbar-dark navbar-set" aria-label="Third navbar example">
        <div class="container-fluid">
          <a class="navbar-brand brand" href="{% url 'portfolio:home' %}">Ilya Berezenko</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbartogglecontent" aria-controls="navbartogglecontent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbartogglecontent">
            <ul class="navbar-nav me-auto mb-2 mb-sm-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'portfolio:projects' %}">Projects</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'portfolio:contacts' %}">Contacts</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
  </header>
{% block content %}{% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</body>
</html>

templates/portfolio_templates/contacts.html
{% extends 'portfolio_templates/base.html' %}

{% block head %}
{% load static %}
<title>Contacts</title>
<link rel="stylesheet" href="{% static 'css/stylecontacts.css' %}">
{% endblock %}

{% block content %}
<main>

    <section class="row justify-content-center">

        <article class="github">
            <img src="{% static 'contact_icons/GitHub-Mark-Light-64px.png' %} " height="64" width="64">
            <a href="https://github.com/FickleIlya" target="_blank">GitHub</a>
        </article>

        <article class="linkedin">
            <img src="{% static 'contact_icons/linkedin-64.png' %}" height="64" width="64">
            <a href="https://www.linkedin.com/in/fickleilya/" target="_blank">LinkedIn</a>
        </article>

        <article class="telegram">
            <img src="{% static 'contact_icons/telegram-64.png' %}" height="64" width="64">
            <a href="https://t.me/thebest47" target="_blank">Telegram</a>
        </article>

        <article class="mail">
            <img src="{% static 'contact_icons/mail.png' %}" height="64" width="64">
            <a href="mailto:berezenkoilya@gmail.com?subject=Portfolio&body=Hi!">Mail</a>
        </article>

    </section>

</main>

{% endblock %}

templates/portfolio_templates/homepage.html
{% extends 'portfolio_templates/base.html' %}

{% block head %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/stylehomepage.css' %}">
<title>Portfolio</title>

{% endblock %}

{% block content %}

<main>
      <div class="container col-xxl-8 px-4 py-5">
        <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
          <div class="col-10 col-sm-8 col-lg-6 me-img">
            <img src="{% static 'me.jpg' %}" class="d-block mx-lg-auto img-fluid" alt="This place only for me!" width="700" height="500" loading="lazy">
          </div>
          <div class="col-lg-6">
            <h1 class="display-5 fw-bold lh-1 mb-3">Hi! I'm Ilya Berezenko,<br>Python Backend Developer</h1>
            <div class="d-grid gap-2 d-md-flex justify-content-md-start div-btn">

              <a href="{% static 'ResumeRus.pdf' %}" class="btn-lg px-4 me-md-2 btn-resume" target="_blank">
                Download ResumeRUS
              </a>
            </div>

            <div class="d-grid gap-2 d-md-flex justify-content-md-start div-btn">
              <a href="{% static 'ResumeEng.pdf' %}" class="btn-lg px-4 me-md-2 btn-resume" target="_blank">
                Download ResumeENG
              </a>
            </div>
          </div>
        </div>
      </div>
</main>

{% endblock %}

templates/portfolio_templates/projects.html
{% extends 'portfolio_templates/base.html' %}

{% block head %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/styleprojects.css' %}">
<title>Projects</title>

{% endblock %}

{% block content %}

<main>
    <section>
        {% for project in projects %}

        <article>

            {% if project.url %}
                <a href="{{ project.url }}" target="_blank">{{ project.title }}</a>
            {% else %}
                {{ project.title }}
            {% endif %}
            <p>{{ project.description }}</p>
        </article>
        {% endfor %}
    </section>
</main>

{% endblock %}